package raw

/*
#cgo CFLAGS: -I../
#cgo LDFLAGS: -lspinners
#include "spinner.h"
*/
import "C"

type Cstring = *C.char

type Spinner_t = C.spinner_t

type Spinner_spinners_t = C.spinner_spinners_t

const (
	SPINNER_SPINNERS_DOTS Spinner_spinners_t = iota
	SPINNER_SPINNERS_DOTS2
	SPINNER_SPINNERS_DOTS3
	SPINNER_SPINNERS_DOTS4
	SPINNER_SPINNERS_DOTS5
	SPINNER_SPINNERS_DOTS6
	SPINNER_SPINNERS_DOTS7
	SPINNER_SPINNERS_DOTS8
	SPINNER_SPINNERS_DOTS9
	SPINNER_SPINNERS_DOTS10
	SPINNER_SPINNERS_DOTS11
	SPINNER_SPINNERS_DOTS12
	SPINNER_SPINNERS_DOTS8BIT
	SPINNER_SPINNERS_LINE
	SPINNER_SPINNERS_LINE2
	SPINNER_SPINNERS_PIPE
	SPINNER_SPINNERS_SIMPLEDOTS
	SPINNER_SPINNERS_SIMPLEDOTSSCROLLING
	SPINNER_SPINNERS_STAR
	SPINNER_SPINNERS_STAR2
	SPINNER_SPINNERS_FLIP
	SPINNER_SPINNERS_HAMBURGER
	SPINNER_SPINNERS_GROWVERTICAL
	SPINNER_SPINNERS_GROWHORIZONTAL
	SPINNER_SPINNERS_BALLOON
	SPINNER_SPINNERS_BALLOON2
	SPINNER_SPINNERS_NOISE
	SPINNER_SPINNERS_BOUNCE
	SPINNER_SPINNERS_BOXBOUNCE
	SPINNER_SPINNERS_BOXBOUNCE2
	SPINNER_SPINNERS_TRIANGLE
	SPINNER_SPINNERS_ARC
	SPINNER_SPINNERS_CIRCLE
	SPINNER_SPINNERS_SQUARECORNERS
	SPINNER_SPINNERS_CIRCLEQUARTERS
	SPINNER_SPINNERS_CIRCLEHALVES
	SPINNER_SPINNERS_SQUISH
	SPINNER_SPINNERS_TOGGLE
	SPINNER_SPINNERS_TOGGLE2
	SPINNER_SPINNERS_TOGGLE3
	SPINNER_SPINNERS_TOGGLE4
	SPINNER_SPINNERS_TOGGLE5
	SPINNER_SPINNERS_TOGGLE6
	SPINNER_SPINNERS_TOGGLE7
	SPINNER_SPINNERS_TOGGLE8
	SPINNER_SPINNERS_TOGGLE9
	SPINNER_SPINNERS_TOGGLE10
	SPINNER_SPINNERS_TOGGLE11
	SPINNER_SPINNERS_TOGGLE12
	SPINNER_SPINNERS_TOGGLE13
	SPINNER_SPINNERS_ARROW
	SPINNER_SPINNERS_ARROW2
	SPINNER_SPINNERS_ARROW3
	SPINNER_SPINNERS_BOUNCINGBAR
	SPINNER_SPINNERS_BOUNCINGBALL
	SPINNER_SPINNERS_SMILEY
	SPINNER_SPINNERS_MONKEY
	SPINNER_SPINNERS_HEARTS
	SPINNER_SPINNERS_CLOCK
	SPINNER_SPINNERS_EARTH
	SPINNER_SPINNERS_MATERIAL
	SPINNER_SPINNERS_MOON
	SPINNER_SPINNERS_RUNNER
	SPINNER_SPINNERS_PONG
	SPINNER_SPINNERS_SHARK
	SPINNER_SPINNERS_DQPB
	SPINNER_SPINNERS_WEATHER
	SPINNER_SPINNERS_CHRISTMAS
	SPINNER_SPINNERS_GRENADE
	SPINNER_SPINNERS_POINT
	SPINNER_SPINNERS_LAYER
	SPINNER_SPINNERS_BETAWAVE
	SPINNER_SPINNERS_FINGERDANCE
	SPINNER_SPINNERS_FISTBUMP
	SPINNER_SPINNERS_SOCCERHEADER
	SPINNER_SPINNERS_MINDBLOWN
	SPINNER_SPINNERS_SPEAKER
	SPINNER_SPINNERS_ORANGEPULSE
	SPINNER_SPINNERS_BLUEPULSE
	SPINNER_SPINNERS_ORANGEBLUEPULSE
	SPINNER_SPINNERS_TIMETRAVEL
	SPINNER_SPINNERS_AESTHETIC
)

func Spinner_new(spinner Spinner_spinners_t, message Cstring) Spinner_t {
	return C.spinner_new(spinner, message)
}

func Spinner_new_with_timer(spinner Spinner_spinners_t, message Cstring) Spinner_t {
	return C.spinner_new_with_timer(spinner, message)
}

func Spinner_stop(spinner *Spinner_t) {
	C.spinner_stop(spinner)
}

func Spinner_stop_with_symbol(spinner *Spinner_t, symbol Cstring) {
	C.spinner_stop_with_symbol(spinner, symbol)
}

func Spinner_stop_with_newline(spinner *Spinner_t) {
	C.spinner_stop_with_newline(spinner)
}

func Spinner_stop_with_message(spinner *Spinner_t, msg Cstring) {
	C.spinner_stop_with_message(spinner, msg)
}

func Spinner_stop_and_persist(spinner *Spinner_t, symbol Cstring, msg Cstring) {
	C.spinner_stop_and_persist(spinner, symbol, msg)
}

func Spinner_clean(spinner *Spinner_t) {
	C.spinner_clean(spinner)
}
